name: gardening_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  speech_to_text: ^7.0.0
  http: ^1.2.0
  provider: ^6.1.2
  permission_handler: ^12.0.0+1
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env